api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/vendor/bagrinsergiu/sylius/src/Sylius/Bundle/ApiBundle/Resources/config/api_resources'
            - '%kernel.project_dir%/config/api_platform'
            - '%kernel.project_dir%/src/Entity'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
