---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sylius-mysql-pv
  labels:
    type: local
    app: sylius-mysql
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/k8s-volumes/sylius-mysql-volume"

