---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: sylius-deployment
spec:
    selector:
        matchLabels:
            app: &label-app sylius
    replicas: 1
    template:
        metadata:
            labels:
                app: *label-app
        spec:
            containers:
                - name: sylius
                  image: public.ecr.aws/n7j9k3k1/sylius:latest
                  resources:
                      requests:
                          memory: "256Mi"
                          cpu: "250m"
                      limits:
                          memory: "1024Mi"
                          cpu: "500m"
                  ports:
                      - containerPort: 80
                  env:
                      - name: APP_ENV
                        valueFrom:
                            configMapKeyRef:
                                name: sylius-config
                                key: symfony-env
                      - name: APP_SECRET
                        valueFrom:
                            secretKeyRef:
                                name: sylius-secret
                                key: symfony-app-secret
                      - name: DATABASE_URL
                        valueFrom:
                            secretKeyRef:
                                name: sylius-secret
                                key: symfony-database-url
                      - name: APP_DEBUG
                        value: "1"
                      - name: PHP_DATE_TIMEZONE
                        value: "UTC"  
                  livenessProbe:
                      httpGet:
                          port: 80
                          path: /
                  readinessProbe: &readiness-probe
                      httpGet:
                          port: 80
                          path: /
                  startupProbe:
                      << : *readiness-probe
                      failureThreshold: 30
