apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: sylius-secret
data:
  symfony-app-secret: MTdlY2FiMGU3ZTMxMDg0ZjM3ODcyZGEwZTE4ZmQ3MmU=
  symfony-database-url: bXlzcWw6Ly9yb290OnN5bGl1c0BzeWxpdXMtbXlzcWw6MzMwNi9zeWxpdXM=
  mysql-root-password: c3lsaXVz
